# Add informacion a Big Query

In [33]:
import pandas as pd
import os
import json
from datetime import datetime
import pytz
from dotenv import load_dotenv
from google.cloud import bigquery
import pandas_gbq

pd.set_option("display.max_columns", None)

In [34]:
load_dotenv()

project_id = os.getenv("GCP_PROJECT_ID")
dataset_id = os.getenv("BQ_DATASET_ID")
table_id = os.getenv("BQ_TABLE_ID")
credentials_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

print("Proyecto:", project_id)
print("Dataset:", dataset_id)
print("Tabla:", table_id)
print("Credencial:", credentials_path)

Proyecto: gcp-data-bigquery-prod-us-east
Dataset: hist_table
Tabla: input_data
Credencial: secrets/SA-gcp-data-bigquery-prod-us-east-8ef5fac44549.json

In [35]:
# Periodo
AAAAMM = '202606'

In [36]:
df = pd.read_csv('./data/raw/test.csv', sep = ',')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,6,1998,1998,Gable,CompShg,VinylSd,VinylSd,BrkFace,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926,678,0,1604,0.0,0.0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360,36,0,0,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1992,1992,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280,0,0,1280,0.0,0.0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0,82,0,0,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,Twnhs,2Story,4,7,1970,1970,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,546.0,546.0,GasA,Gd,Y,SBrkr,546,546,0,1092,0.0,0.0,1,1,3,1,TA,5,Typ,0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,TwnhsE,2Story,4,5,1970,1970,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,252.0,Unf,0.0,294.0,546.0,GasA,TA,Y,SBrkr,546,546,0,1092,0.0,0.0,1,1,3,1,TA,6,Typ,0,NaN,CarPort,1970.0,Unf,1.0,286.0,TA,TA,Y,0,24,0,0,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1Story,5,7,1960,1996,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,ALQ,1224.0,Unf,0.0,0.0,1224.0,GasA,Ex,Y,SBrkr,1224,0,0,1224,1.0,0.0,1,0,4,1,TA,7,Typ,1,TA,Detchd,1960.0,Unf,2.0,576.0,TA,TA,Y,474,0,0,0,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,SFoyer,5,5,1992,1992,Gable,CompShg,HdBoard,Wd Shng,NaN,0.0,TA,TA,PConc,Gd,TA,Av,GLQ,337.0,Unf,0.0,575.0,912.0,GasA,TA,Y,SBrkr,970,0,0,970,0.0,1.0,1,0,3,1,TA,6,Typ,0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,80,32,0,0,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,Norm,1Fam,2Story,7,5,1993,1994,Gable,CompShg,HdBoard,HdBoard,BrkFace,94.0,TA,TA,PConc,Gd,TA,Av,LwQ,758.0,Unf,0.0,238.0,996.0,GasA,Ex,Y,SBrkr,996,1004,0,2000,0.0,0.0,2,1,3,1,TA,9,Typ,1,TA,Attchd,1993.0,Fin,3.0,650.0,TA,TA,Y,190,48,0,0,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [37]:
with open("./scripts/rename_columns.json", "r", encoding="utf-8") as archivo:
    dictRename = json.load(archivo)
print(type(dictRename))
print(dictRename)

<class 'dict'>
{'Id': 'id', 'MSSubClass': 'mssubclass', 'MSZoning': 'mszoning', 'LotFrontage': 'lotfrontage', 'LotArea': 'lotarea', 'Street': 'street', 'Alley': 'alley', 'LotShape': 'lotshape', 'LandContour': 'landcontour', 'Utilities': 'utilities', 'LotConfig': 'lotconfig', 'LandSlope': 'landslope', 'Neighborhood': 'neighborhood', 'Condition1': 'condition', 'Condition2': 'condition_secundaria', 'BldgType': 'bldgtype', 'HouseStyle': 'housestyle', 'OverallQual': 'overallqual', 'OverallCond': 'overallcond', 'YearBuilt': 'yearbuilt', 'YearRemodAdd': 'yearremodadd', 'RoofStyle': 'roofstyle', 'RoofMatl': 'roofmatl', 'Exterior1st': 'exterior_principal', 'Exterior2nd': 'exterior_secundario', 'MasVnrType': 'masvnrtype', 'MasVnrArea': 'masvnrarea', 'ExterQual': 'exterqual', 'ExterCond': 'extercond', 'Foundation': 'foundation', 'BsmtQual': 'bsmtqual', 'BsmtCond': 'bsmtcond', 'BsmtExposure': 'bsmtexposure', 'BsmtFinType1': 'bsmtfintype_principal', 'BsmtFinSF1': 'bsmtfinsf_principal', 'BsmtFinType2': 'bsmtfintype_secundario', 'BsmtFinSF2': 'bsmtfinsf_secundario', 'BsmtUnfSF': 'bsmtunfsf', 'TotalBsmtSF': 'totalbsmtsf', 'Heating': 'heating', 'HeatingQC': 'heatingqc', 'CentralAir': 'centralair', 'Electrical': 'electrical', '1stFlrSF': 'firstflrsf', '2ndFlrSF': 'secondflrsf', 'LowQualFinSF': 'lowqualfinsf', 'GrLivArea': 'grlivarea', 'BsmtFullBath': 'bsmtfullbath', 'BsmtHalfBath': 'bsmthalfbath', 'FullBath': 'fullbath', 'HalfBath': 'halfbath', 'BedroomAbvGr': 'bedroomabvgr', 'KitchenAbvGr': 'kitchenabvgr', 'KitchenQual': 'kitchenqual', 'TotRmsAbvGrd': 'totrmsabvgrd', 'Functional': 'functional', 'Fireplaces': 'fireplaces', 'FireplaceQu': 'fireplacequ', 'GarageType': 'garagetype', 'GarageYrBlt': 'garageyrblt', 'GarageFinish': 'garagefinish', 'GarageCars': 'garagecars', 'GarageArea': 'garagearea', 'GarageQual': 'garagequal', 'GarageCond': 'garagecond', 'PavedDrive': 'paveddrive', 'WoodDeckSF': 'wooddecksf', 'OpenPorchSF': 'openporchsf', 'EnclosedPorch': 'enclosedporch', '3SsnPorch': 'ssnporch', 'ScreenPorch': 'screenporch', 'PoolArea': 'poolarea', 'PoolQC': 'poolqc', 'Fence': 'fence', 'MiscFeature': 'miscfeature', 'MiscVal': 'miscval', 'MoSold': 'mosold', 'YrSold': 'yrsold', 'SaleType': 'saletype', 'SaleCondition': 'salecondition'}

In [38]:
df = df.rename(columns=dictRename)
df.dtypes

id                 int64
mssubclass         int64
mszoning          object
lotfrontage      float64
lotarea            int64
                  ...
miscval            int64
mosold             int64
yrsold             int64
saletype          object
salecondition     object
Length: 80, dtype: object

In [39]:
ZPeru = pytz.timezone("America/Lima")
fecha_carga = datetime.now(ZPeru)
df['date_subida_local'] = fecha_carga.replace(tzinfo=None)
df['date_subida_utc'] = fecha_carga.astimezone(pytz.UTC)
df['periodo'] = AAAAMM

colOrden = ['id','periodo'] + [col for col in df.columns if col not in ('id','periodo')]

df = df[colOrden]

df.head()

,id,periodo,mssubclass,mszoning,lotfrontage,lotarea,street,alley,lotshape,landcontour,utilities,lotconfig,landslope,neighborhood,condition,condition_secundaria,bldgtype,housestyle,overallqual,overallcond,yearbuilt,yearremodadd,roofstyle,roofmatl,exterior_principal,exterior_secundario,masvnrtype,masvnrarea,exterqual,extercond,foundation,bsmtqual,bsmtcond,bsmtexposure,bsmtfintype_principal,bsmtfinsf_principal,bsmtfintype_secundario,bsmtfinsf_secundario,bsmtunfsf,totalbsmtsf,heating,heatingqc,centralair,electrical,firstflrsf,secondflrsf,lowqualfinsf,grlivarea,bsmtfullbath,bsmthalfbath,fullbath,halfbath,bedroomabvgr,kitchenabvgr,kitchenqual,totrmsabvgrd,functional,fireplaces,fireplacequ,garagetype,garageyrblt,garagefinish,garagecars,garagearea,garagequal,garagecond,paveddrive,wooddecksf,openporchsf,enclosedporch,ssnporch,screenporch,poolarea,poolqc,fence,miscfeature,miscval,mosold,yrsold,saletype,salecondition,date_subida_local,date_subida_utc
0,1461,202606,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,2026-08-06 17:12:26.371703,2026-08-06 22:12:26.371703+00:00
1,1462,202606,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,2026-08-06 17:12:26.371703,2026-08-06 22:12:26.371703+00:00
2,1463,202606,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,2026-08-06 17:12:26.371703,2026-08-06 22:12:26.371703+00:00
3,1464,202606,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,6,1998,1998,Gable,CompShg,VinylSd,VinylSd,BrkFace,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926,678,0,1604,0.0,0.0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360,36,0,0,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal,2026-08-06 17:12:26.371703,2026-08-06 22:12:26.371703+00:00
4,1465,202606,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1992,1992,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280,0,0,1280,0.0,0.0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0,82,0,0,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal,2026-08-06 17:12:26.371703,2026-08-06 22:12:26.371703+00:00

In [40]:
destination_table = f"{dataset_id}.{table_id}"
full_table_id = f"{project_id}.{destination_table}"
print(destination_table)

client = bigquery.Client(project=project_id)

cantidad_esperada = len(df)


query_delete = f"""
    DELETE FROM `{full_table_id}` WHERE periodo = '{AAAAMM}'
"""
print("Ejecutando DELETE TABLE...")

delete_job = client.query(query_delete)
delete_job.result()

print(f"Tabla vaciada correctamente para el periodo {AAAAMM}✅")

print("Iniciando carga del DataFrame...")

pandas_gbq.to_gbq(df , destination_table, if_exists='append', project_id=project_id)

print("Proceso de carga finalizado.")

# ---------------------------------------

hist_table.input_data
Ejecutando DELETE TABLE...
Tabla vaciada correctamente para el periodo 202606✅
Iniciando carga del DataFrame...
Proceso de carga finalizado.